name: Deploy .NET Core Application to Azure Web App

on:
  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: couchavalon

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp

    - name: Deploy Entity Framework Migrations
      uses: benday-inc/deploy-ef-core-migration@main
      with: 
        path_to_directory: '${{ github.workspace }}/dotnetcorewebapp'
        migrations_dll: 'MultiplayerAvalon.EntityFrameworkCore.dll'
        migrations_namespace: 'MultiplayerAvalon.EntityFrameworkCore'
        startup_dll: 'MultiplayerAvalon.Web.Host.dll'
        dbcontext_class_name: 'MultiplayerAvalonDbContext'

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './dotnetcorewebapp'